kubernetes-sigs/cluster-api-provider-nested

- main.go
:warning: This changes the flag names, but given this isn't being used yet, I don't think it matters.
> ⚠️ changing flag names

- PROJECT
- api/v1alpha4/groupversion_info.go
- config/crd/bases/controlplane.cluster.x.k8s.io_nestedcontrolplanes.yaml
- config/crd/kustomization.yaml
- config/crd/patches/cainjection_in_nestedcontrolplanes.yaml
- config/crd/patches/webhook_in_nestedcontrolplanes.yaml
- config/rbac/nestedcontrolplane_editor_role.yaml
- config/rbac/nestedcontrolplane_viewer_role.yaml
- config/rbac/role.yaml
- controllers/nestedcontrolplane_controller.go
Kubernetes won't allow any CRDs to be registered under the `k8s.io` domain, the original this was supposed to be `x-k8s.io` to match other k8s extensions.
> Switch to proper x-k8s.io domain

- go.mod
- go.sum
Now that the official CR 0.7.0 release came out this moves away from the alpha dependency.
> Updating controller-runtime to 0.7.0

- Makefile
Fixed https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/50
> Do not add slash for REGISTRY with non google cloud

- virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Leave the CABundle field unset for VC validation webhook configuration, which allows APIServer to use system trusted roots on the APIServer to validate the webhook certificate.
> [VC] unset the VC validation webhook CABundle

- Makefile
Removes final reference to `master`.
closes #65 
Ref #47 
> 🐛  fixing branch name for apidiff

- scripts/ci-build.sh
- scripts/ci-make.sh
- scripts/ci-test.sh
This adds `virtualcluster/` subdirectory to the prow presubmit, this will allow us to validate if changes in PRs break VC or CAPN.
closes #64 
/milestone v0.1.x
/kind cleanup
> ✨ Adding virtualcluster to prow

- docs/README.md
> Bugfix: fix error in quick start guide

- docs/README.md
Sometimes people want to run multiple kind clusters to have different test purpose, it is better to add a name for the kind cluster for capn as well.
> Setting kind name as CAPN

- virtualcluster/cmd/vn-agent/app/options/options.go
- virtualcluster/cmd/vn-agent/app/server.go
- virtualcluster/go.sum
- virtualcluster/pkg/controller/controllers/suite_test.go
- virtualcluster/pkg/vn-agent/server/server.go
- virtualcluster/pkg/vn-agent/server/test/go.sum
- virtualcluster/pkg/vn-agent/server/test/server_test.go
This add the ability to use vn-agent with a `kubeconfig` specified, which works for the Deployment style vs the DaemonSet mechanism as well this added a `/healthz` endpoint for better checking of it's availability.
> 🌱  VN Agent Healthz Checks

- virtualcluster/Dockerfile
When purely using the `virtualcluster/Dockerfile` and not using the `make build-images` target the older version of golang is incompatible with the latest `controller-runtime`. The original `make` target still works without this change which is why it wasn't caught.
> 🌱 [VC] Adding go:1.16.2 docker image for VC

- Makefile
This fixes the builds which were erroring cause of GCP projects for releasing the images.
XRef: #91 
> 🐛  Updating staging and prod registries

- virtualcluster/doc/demo.md
I guess the `virtual cluster`'s original address is in the `multi-tenancy` : )
> Fix incorrect git address

- Makefile
- hack/tools/release/notes.go
I fixed related issue in CAPI by PR https://github.com/kubernetes-sigs/cluster-api/pull/4796. And this PR is fixing for the issue https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/118.
After fixes, the cli `make release-notes` works well now:
```
fenglixa@fenglixas-MacBook-Pro  ~/go/src/github.com/kubernetes-sigs/cluster-api-provider-nested   main ±  make release-notes
(unset)
cd hack/tools && go build -tags=tools -o bin/release-notes ./release
hack/tools/bin/release-notes
Changes since v0.1.0
---
_Thanks to all our contributors!_ 😊
fenglixa@fenglixas-MacBook-Pro  ~/go/src/github.com/kubernetes-sigs/cluster-api-provider-nested   main ±  ll hack/tools/bin/release-notes
-rwxr-xr-x  1 fenglixa  staff  2484176 Jun 10 18:55 hack/tools/bin/release-notes
```
Fixes …
> 🐛Fix the issue of make release-notes in cluster-api-provider-nested

- metadata.yaml
to support #54 we need `clusterctl` to be able to marshal this file and even the `v0.4.0-beta.0` release doesn't have `v1alpha4` `clusterctl` support.
closes #119 
/kind bug
/milestone v0.1.x
> 🐛 metadata.yaml clusterctl version to v1alpha3

- Makefile
- templates/cluster-template.yaml
This will enable us to use `clusterctl generate config` to create the sample configs for deploying a cluster.
Fixes #124
/milestone v0.1.x
/kind feature
> ✨ Adding cluster-template.yaml for clusterctl

- virtualcluster/doc/demo.md
Fixes #
The `ValidatingWebhookConfiguration` not clear when remove `virtual cluster` stuff, since it created by `vc-manager` and not belong to `namespace`
> Remove ValidatingWebhookConfiguration when clearing all virtual cluster stuff

- virtualcluster/config/setup/all_in_one.yaml
- virtualcluster/doc/demo.md
- virtualcluster/experiment/doc/demo.md
I accidentally renamed instead of copying the manifest which broke the demo docs. This reverts those changes.
Reverts #142
Reverts #136 
Specifically that the all_in_one.yaml was just supposed to be copied while we transition from vc-manager provisioned to capi provisioned.
> 🐛 Adding back original all_in_one.yaml for VC

- virtualcluster/doc/customresource-syncer.md
**What this PR does / why we need it**
It's `labels` to enable the `CRD` syncer not `annotation`.
> Correct the description for crd syncer

- virtualcluster/config/setup/all_in_one.yaml
- virtualcluster/config/setup/all_in_one_aliyun.yaml
- virtualcluster/config/setup/all_in_one_capi.yaml
- virtualcluster/doc/customresource-syncer.md
When I create a `ns` in tenant cluster then delete I found error raised in `syncer` 's  log, as this:
```
E0702 05:42:20.820948       1 dws.go:95] failed reconcile secret test/default-token-zp82r DELETE of cluster default-a32f71-vc-sample-1 secrets is forbidden: User "system:serviceaccount:vc-manager:vc-syncer" cannot deletecollection resource "secrets" in API group "" in the namespace "default-a32f71-vc-sample-1-test"
```
seems we do not assign enough permission to the `sa`, leak for `deletecollection`
> Add permission for secret deletecollect

- templates/cluster-template-certmanager.yaml
Use cert-manager to manage the PKI for the NCP components.
> ✨ Add certmanager flavor

- virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
In #145 , we use self-signed certificate for `ValidatingWebhookConfiguration`, that's means we will generate self-signed CA when `vc-manager` startup.
Based on current implements, when creating `ValidatingWebhookConfiguration` and found it already exist we will give up to create a new one and expect to use the older one, that's will cause problem since the `private key` is re-generated by new CA but in old `ValidatingWebhookConfiguration` included the old `CA`, that's will case the webhook raise:
```
root@rentz1:~# kubectl delete VirtualCluster vc-sample-1
Error from server (InternalError): Internal error occurred: failed calling webhook "virtualcluster.validating.webhook": Post "https://virtualcluster-webhook-service.vc-manager.svc:9443/validate-ten …
```
> Remove old webhookconfiguration if it alreasy exist before create new one

- virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
- virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
- virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
- virtualcluster/pkg/controller/pki/pki.go
- virtualcluster/pkg/controller/secret/secret.go
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/166
@christopherhein @Fei-Guo 
This PR only covered VirtualCluster but does not cover nested control plane, will fix nested control plane in another PR.
@wangjsty ^^
> ✨ Enabled Aggregate API for Virtual Cluster

- virtualcluster/pkg/syncer/resources/configmap/checker.go
- virtualcluster/pkg/syncer/resources/crd/checker.go
- virtualcluster/pkg/syncer/resources/endpoints/checker.go
- virtualcluster/pkg/syncer/resources/ingress/checker.go
- virtualcluster/pkg/syncer/resources/namespace/checker.go
- virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
- virtualcluster/pkg/syncer/resources/pod/checker.go
- virtualcluster/pkg/syncer/resources/priorityclass/checker.go
- virtualcluster/pkg/syncer/resources/secret/checker.go
- virtualcluster/pkg/syncer/resources/service/checker.go
- virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
- virtualcluster/pkg/syncer/resources/storageclass/checker.go
When `patrols` started and no `virtualcluster`, it keep report ignore information(since no virtualcluster available), like this:
```
I0712 07:09:12.135835       1 checker.go:53] tenant masters has no clusters, give up period checker
I0712 07:09:12.159229       1 checker.go:52] tenant masters has no clusters, give up period checker
I0712 07:09:12.257849       1 checker.go:51] tenant masters has no clusters, give up storage class period checker
I0712 07:09:12.936675       1 checker.go:53] tenant masters has no clusters, give up period checker
I0712 07:09:13.027904       1 checker.go:55] tenant masters has no clusters, give up period checker
I0712 07:09:13.323316       1 checker.go:56] tenant masters has no clusters, give up period checker
I0712 …
```
> 🌱 Add useful information for patroller log lines

- virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
- virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
Fixes #
`--requestheader-allowed-names=""` indicates to an extension apiserver that any CN is acceptable.
Here we should use CN name `front-proxy-client ` which is more secure.
/cc @chrishenzie @Fei-Guo
> Use front-proxy-client CN for aggregate API

- virtualcluster/doc/customresource-syncer.md
The sample CRD definition hould be `Foo`
> Correct sample for crd syncer

- Dockerfile
time to time, my env stuck at download this restart.sh and start.sh those files are used for Tilt and not needed at capi 0.4.0 ,so remove them 
further info can refer https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/761
Fixes #
> Remove restart.sh and start.sh in docker file

- virtualcluster/pkg/syncer/resources/pod/checker.go
- virtualcluster/pkg/syncer/resources/service/checker.go
- virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
bugfix: remove invalid cluster name from knownClusterSet 
Fixes #
> vc-syncer: remove invalid cluster name from knownClusterSet

- virtualcluster/cmd/kubectl-vc/exec.go
Run `kubectl-vc exec` to move to tenant's workspace then run `exit` to exit.
should remove `kubeconfig` file for the tenant which generated by `kubectl-vc exec`.
Fixes #
> Remove related kubeconfig file when exit

- virtualcluster/cmd/syncer/app/options/options.go
- virtualcluster/pkg/syncer/apis/config/types.go
DisableServiceAccountToken is ambiguous about the scope of ServiceAccountTokens that it is disabling(host vs tenant) and could lead to mis-configuration that could lead to security problems as a reasonable person might want service account tokens in their pods, but certainly not HostServiceAccountTokens in most cases.
Usage: 
- [set pod.Spec.AutomountServiceAccountToken](https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/2aa1c8cf8533419e790a56c2b68ba2fdfe04f9ae/virtualcluster/pkg/syncer/conversion/mutate.go#L391).
> 📖 Update documentation for DisableServiceAccountToken

- virtualcluster/pkg/syncer/resources/pod/dws.go
- virtualcluster/pkg/syncer/resources/pod/dws_test.go
Remove a check for optional secrets in pod syncer. The pod resource syncer checks that all secrets defined in volumes in the pod spec exist in the virtual cluster. The intent is to ensure that service account tokens exist before the pod is scheduled. The minimal change is to only verify secrets that are marked as required. If it's optional, we remove it from the check.
We should confirm that ignoring optional doesn't compromise any of the security assumptions of the current model in terms of us making sure a service account token is properly synced before a pod is created.
We do already enforce this behavior with syncer optionally setting AutomountServiceAccountToken on the sync'd pods spec:
- …
> 🐛 VC-Syncer - remove check for optional secret Volumes on Pods

- controlplane/nested/PROJECT
Remove wrongly added space in PROJECT file, because it affects generating new api with kubebuilder.
Fixes #
> Remove additional space in PROJECT file

- virtualcluster/pkg/syncer/metrics/metrics.go
**What this PR does / why we need it**: there is a misspelling in the Prometheus metric, which makes confusion and makes automation more difficult
> 🌱 Fix misspell in checker_scan_duration_seconds metric

- virtualcluster/config/crd/tenancy.x-k8s.io_virtualclusters.yaml
- virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
The current cluster listing is useless:
```
NAME         AGE
dev          24m
dev2         4s
```
We should improve CRD to add columns, like:
```
NAME          AGE     PHASE     CLUSTERVERSION
dev           3m58s   Running   v1-18
dev2          6m55s   Running   v1-19
```
and with `-o wide` 
```
NAME         AGE     PHASE     CLUSTERVERSION   CLUSTERNAMESPACE
dev          0s      Pending   v1-18            kcs-071942-dev
dev2         2m57s   Running   v1-19            kcs-a39dce-dev2
```
We should probably change https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/Makefile#L114 to `output:crd:dir=./config/crd` as it do nothing now
> 🌱 Add additionalPrinterColumns to VirtualCluster CRD

- virtualcluster/cmd/manager/main.go
- virtualcluster/pkg/controller/controller.go
- virtualcluster/pkg/controller/controllers/provisioner/provisioner_aliyun.go
- virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
- virtualcluster/pkg/controller/controllers/suite_test.go
- virtualcluster/pkg/controller/controllers/virtualcluster_controller.go
Today the manager will timeout after 180seconds and stop trying to deploy the control plane. This causes problems if someone is trying to create a cluster when there is super cluster issues happening.
The  PR allows to configure timeout with `--provisioner-timeout` flag for manager.
> 🌱 Configurable wait time on VirtualCluster Controller for control plane bring up

- virtualcluster/cmd/syncer/app/server.go
Syncer non-leader pod could be stuck in CrashLoopBackOff because of /healthz unavailable when LeaderElection does not hit the leader callback.
The PR moves /healthz server, pprof server and /metrics listeners outside of leader election logic, allowing them to be available always.
> 🐛 Fix non-leader crashloop

- virtualcluster/pkg/util/cluster/cluster.go
When the cluster cache is not fully ready and getCache returns an error, the cancel function is not assigned. This will cause panic when the cluster removal process starts.
Fixes #
> 🐛 Fix cancel function nil problem

- virtualcluster/cmd/vn-agent/app/options/options.go
- virtualcluster/cmd/vn-agent/app/server.go
- virtualcluster/pkg/vn-agent/server/metrics.go
- virtualcluster/pkg/vn-agent/server/route.go
- virtualcluster/pkg/vn-agent/server/server.go
The pr enabled metrics server for vn-agent instrumenting all the API Calls to super API Server or Kubelet and counting all the API Calls with respect to host, tenantName, tenantNamespace, action and responseCode.
**Which issue(s) this PR fixes**
Fixes #251
> ✨Enabling Metrics for vn-agent

- virtualcluster/cmd/syncer/app/options/options.go
- virtualcluster/pkg/syncer/apis/config/types.go
The default hardcoded 30 second timeout for the super cluster isn't enough under some scenarios, this allows that to be additionally supplied from a CLI flag but still uses the standard default if not supplied.
> ✨ Supporting Super Cluster Timeout Overrides

- controlplane/nested/controllers/nestedcontrolplane_controller.go
**What this PR does / why we need it**: The current logic for adding owner reference seems to have a problem: if we can cast the error to `AlreadyOwnedError`, then it means the owner reference has already been added, and we should move on. However, currently the logic is if the owner reference is added, it will emit that error.
Fixes #
> 🐛 Fix nested control plane object owner reference

- virtualcluster/pkg/syncer/resources/configmap/checker.go
- virtualcluster/pkg/syncer/resources/crd/checker.go
- virtualcluster/pkg/syncer/resources/endpoints/checker.go
- virtualcluster/pkg/syncer/resources/ingress/checker.go
- virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
- virtualcluster/pkg/syncer/resources/pod/checker.go
- virtualcluster/pkg/syncer/resources/priorityclass/checker.go
- virtualcluster/pkg/syncer/resources/secret/checker.go
- virtualcluster/pkg/syncer/resources/service/checker.go
- virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
- virtualcluster/pkg/syncer/resources/storageclass/checker.go
It is useless to have these messages to spam in logs in case the syncer is doing nothing.
Let's move them to the next verbosity level as other debug logs.
> 🌱 Increase log level threshold for "giving up" messages

- controlplane/nested/main.go
- go.mod
- go.sum
- main.go
- virtualcluster/cmd/syncer/app/options/options.go
- virtualcluster/pkg/syncer/apis/config/types.go
- virtualcluster/pkg/syncer/conversion/mutate.go
- virtualcluster/pkg/syncer/conversion/mutate_test.go
- virtualcluster/pkg/syncer/resources/pod/dws.go
DnsOption needs to be entered by users according to their super cluster environment. Add flag to allow user to config DNSOptions
Fixes # N/A
> Add DnsOption Flag to allow user to have customized resolve.conf

- virtualcluster/config/crd/tenancy.x-k8s.io_clusterversions.yaml
- virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
The latest k8s version adopted by `Kind` is `v1.23`, and there are several API is deprecated and not support in the latest version, include:
- MutatingWebhookConfiguration and ValidatingWebhookConfiguration from `v1beta1` to `v1`
- apiextensions.k8s.io from `v1beta1` to `v1`
So update some code snippet to make it works with the new k8s version
> transfer k8s api to meet new version

- virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
- virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
- virtualcluster/pkg/controller/controllers/clusterversion_controller_test.go
- virtualcluster/test/e2e/framework/clusterversion/create.go
With the k8s version 1.22+, the `etcd` cannot install success, since the original annotation is deprecated:
`service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"`
That's make the `coredns` cannot resove the pod(etcd pod) which is not ready.
See the issue:
https://github.com/coredns/coredns/issues/5159#issuecomment-1033726643
> Remove deprecated annotation for SVC, it block the installation of etcd

- virtualcluster/cmd/syncer/app/options/options.go
- virtualcluster/pkg/syncer/apis/config/types.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
- virtualcluster/pkg/syncer/vnode/pod/provider.go
- virtualcluster/pkg/syncer/vnode/pod/provider_test.go
- virtualcluster/pkg/syncer/vnode/vnode.go
This adds the ability to use the `vn-agent` as a `DaemonSet` but uses vn-agent pod IPs as the routable address to configure with the vnode UWS'ed object. Because this interface is used for all syncing any updates to the node status object trigger a reconciliation. We handle vn-agent pod failures with status updates which triggers a resync.
> ⚠️  For anyone implementing this you should have a node level check for example `node-exporter` or an `initContainer` on the vn-agent which updates a condition on the Node or other part of the node object. By doing this the syncer will update all your VirtualClusters VNodes anytime the `vn-agent` is rescheduled, this can be done without rebinding.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
> ✨ Adding VN Agent PodIP Provider

- controlplane/nested/certificate/helpers.go
- controlplane/nested/controllers/nestedapiserver_controller.go
for kubectl exec/log/port forward, vn-agent needs to know the namespace in supercluster, currently it assumes the kubelet-client cert that virtual apiserver uses have the CN as the namespace, so add this hack to make it work. 
Also removed the flag 'kubelet-certificate-authority' in apiserver args because with that virtual apiserver is trying to validate the cert that vn-agent is using, which will fail because the cert doesn't have the pod IP as SAN. 
Fixes #
> use namespace as kubeletclient cert cn because vn-agent expects that for kubectl exec

- controlplane/nested/certificate/helpers.go
- virtualcluster/pkg/syncer/constants/constants.go
- virtualcluster/pkg/syncer/conversion/helper.go
- virtualcluster/pkg/syncer/resources/namespace/dws_test.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
This PR adds a new feature gate `SuperClusterLabelling` which enables adding labels to the namespaces created by syncer.
This behaviour could be extended for any other resources, but starts from namespaces as the particular case. 
**Which issue(s) this PR fixes**:
fixes #272, requires a follow-up with enabling labels for filtering too: https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/1e987ad6c3c6ef0099e898b1b6589975212523b9/virtualcluster/pkg/syncer/resources/namespace/checker.go#L90
The changes are intentionally split by different PRs to allow operator to ensure all namespace are already labelled before reducing the scope of syncer/resources/namespace/checker: garbage collector
> ✨ Add SuperClusterLabelling experimental feature gate

- virtualcluster/pkg/syncer/conversion/helper.go
- virtualcluster/pkg/syncer/resources/namespace/checker.go
- virtualcluster/pkg/syncer/resources/namespace/checker_test.go
- virtualcluster/pkg/syncer/resources/namespace/dws_test.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
The PR is a follow-up feature gate to SuperClusterLabelling https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/273.
It adds new feature gate SuperClusterLabelFilter with namespace checker implementation to allow use label filter requesting super cluster namespaces, instead of doing the full list. It should reduce load to super cluster control plane in multi-platform super clusters (i.e. when super cluster itself is multi-tenant in addition to virtual clusters).
> ✨ Add SuperClusterLabelFilter experimental feature gate

- virtualcluster/pkg/syncer/conversion/helper.go
SuperClusterLabelling was initially created for namespaces, but there are a lot of other objects and controllers created in virtualclusters. The PR adds labeling for all objects too, which could help in the future to use SuperClusterLabelFilter feature gate for any resource. (or even do something like `kubectl get pod -A -l tenancy.x-k8s.io/controlled=true` to find only tenant pods in the Kubernetes cluster).
> ✨ Use SuperClusterLabelling feature gate for all objects if enabled

- virtualcluster/pkg/syncer/resources/configmap/checker.go
- virtualcluster/pkg/syncer/resources/endpoints/checker.go
- virtualcluster/pkg/syncer/resources/ingress/checker.go
- virtualcluster/pkg/syncer/resources/namespace/checker.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
- virtualcluster/pkg/syncer/resources/pod/checker.go
- virtualcluster/pkg/syncer/resources/secret/checker.go
- virtualcluster/pkg/syncer/resources/service/checker.go
- virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
- virtualcluster/pkg/syncer/util/helper.go
#279 introduced labelling for all objects, so this PR adds filtering to all checkers where it is possible.
There are couple checkers (priority class, storage class, persistent volume) that are used for back populating only and have nothing to do with virtual clusters initially, so they still have labels.Everything() selector. All other checkers are used for synchronisation and garbage collecting, so labelling should help to reduce control-plane operations and overall controller memory consumption in clusters, where super-cluster is used outside of nested scope.
> ✨ Use SuperClusterLabelFilter feature gate for all objects if enabled

- virtualcluster/pkg/controller/pki/pki.go
- virtualcluster/pkg/syncer/constants/constants.go
The PR checks the presence of `tenancy.x-k8s.io/external-apiserver-domain` label in VirtualCluster object and adds it contents to the list of altNames.DNSNames in the apiserver certificate, allowing access to the apiserver from outside of the cluster (through an external LoadBalancer service).
This is the responsibility of an operator or other controllers to set that label according to the super-cluster configuration.
> ✨ Add external apiserver domain to the APIServer certificate

- virtualcluster/pkg/controller/controllers/clusterversion_controller_test.go
- virtualcluster/pkg/controller/controllers/metrics.go
- virtualcluster/pkg/controller/controllers/provisioner/provisioner.go
- virtualcluster/pkg/controller/controllers/provisioner/provisioner_aliyun.go
- virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
- virtualcluster/pkg/controller/controllers/suite_test.go
- virtualcluster/pkg/controller/controllers/virtualcluster_controller.go
- virtualcluster/pkg/controller/controllers/virtualcluster_controller_test.go
- virtualcluster/pkg/controller/pki/pki.go
- virtualcluster/pkg/controller/secret/secret.go
- virtualcluster/pkg/syncer/constants/constants.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
- virtualcluster/pkg/util/pki/util.go
The PR adds the featureGate `ClusterVersionPartialUpgrade` to allow native provide to reconcile currently running virtual clusters to re-apply clusterversion specs to control plane.
The PR introduces changes to the current native provisioner (Aliyun just returns `not implemented` for the feature):
1. Use serverSide Apply instead of Create means we can reuse methods to re-apply state, instead of breaking with AlreadyExists conflicts. 
2. Kubernetes client requests are finally share the current context instead of TODO().
3. ClusterVersion must contain apiVersion and kind for each Service and StatefulSet defined (it exists in tests, but could be omitted in real world. Using Patch require them to be set)
### Features of the featureGate
1. The change …
> ✨ Control Plane Upgrades

- .github/workflows/golangci-lint.yml
- virtualcluster/.golangci.yml
- virtualcluster/cmd/vn-agent/app/server.go
- virtualcluster/pkg/controller/controllers/metrics.go
- virtualcluster/pkg/controller/util/net/util.go
- virtualcluster/pkg/syncer/resources/configmap/checker.go
- virtualcluster/pkg/syncer/resources/crd/checker.go
- virtualcluster/pkg/syncer/resources/crd/controller.go
- virtualcluster/pkg/syncer/resources/endpoints/checker.go
- virtualcluster/pkg/syncer/resources/ingress/checker_test.go
- virtualcluster/pkg/syncer/resources/namespace/checker.go
- virtualcluster/pkg/syncer/resources/persistentvolume/checker_test.go
- virtualcluster/pkg/syncer/resources/pod/validationplugin/interface.go
- virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go
- virtualcluster/pkg/syncer/resources/service/checker_test.go
- virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
- virtualcluster/pkg/syncer/resources/serviceaccount/checker_test.go
- virtualcluster/pkg/syncer/resources/storageclass/checker_test.go
- virtualcluster/test/e2e/e2e.go
- virtualcluster/test/e2e/e2e_test.go
- virtualcluster/test/e2e/framework/framework.go
- virtualcluster/test/e2e/framework/text_context.go
- virtualcluster/test/e2e/framework/util.go
- virtualcluster/test/e2e/framework/vc.go
The PR upgrade golangci-lint to the latest and fixes the issues found in it
https://github.com/golangci/golangci-lint/pull/2999
Fixes #291
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/290#discussion_r925997669 and adds the goheader linter to catch Copyright issues
> 🌱 Upgrade golangci-lint to v1.47.2 and fix its issues

- virtualcluster/pkg/syncer/conversion/equality.go
- virtualcluster/pkg/syncer/conversion/helper.go
- virtualcluster/pkg/syncer/resources/crd/checker.go
- virtualcluster/pkg/syncer/resources/crd/controller.go
- virtualcluster/pkg/syncer/resources/crd/uws.go
Updates the CRD types to v1 from v1beta1, v1beta1 was deprecated and when using the crd syncer it will fail to boot on anything above v1.20.
> 🌱 Update CRD Clients to v1

- virtualcluster/pkg/syncer/vnode/vnode.go
**What this PR does / why we need it**: The PR removes confusing excess n.Status.NodeInfo.OperatingSystem assign to Linux, which is not used anywhere and is rewritten in a couple of lines later https://github.com/m-messiah/cluster-api-provider-nested/blob/02b288a700d6ef6fd1776f4d63e3e4a7e0ca317c/virtualcluster/pkg/syncer/vnode/vnode.go#L100
> 🌱 Remove excess NodeInfo.OperatingSystem assign

- virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
- virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
The PR updates sample clusterversions to use k8s 1.22 and adds missing apiVersion/kind fields, required for provisioner.
Note, etcd 3.4 uses ETCDCTL_API=3 by default, so we don't need to prepend this anymore
> 🌱 Update samples with k8s 1.22 and apiVersions

- virtualcluster/pkg/client/clientset/versioned/fake/register.go
- virtualcluster/pkg/client/clientset/versioned/scheme/register.go
- virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
- virtualcluster/pkg/syncer/resources/namespace/checker.go
Currently, etcd certificate is valid for `etcd-0.etcd, etcd-1.etcd, etcd-2.etcd, etcd` names only. That prevents us to connect to etcd from controllers to do health checks, upgrade maintenance or backups without using InsecureSkipVerify.
The PR adds virtualcluster namespace to every etcd domain, so they would be accessible
> 🌱 Add etcd.namespace to the etcd certificate

- virtualcluster/pkg/syncer/conversion/equality.go
- virtualcluster/pkg/syncer/resources/ingress/checker.go
- virtualcluster/pkg/syncer/resources/ingress/checker_test.go
- virtualcluster/pkg/syncer/resources/ingress/controller.go
- virtualcluster/pkg/syncer/resources/ingress/dws.go
- virtualcluster/pkg/syncer/resources/ingress/dws_test.go
- virtualcluster/pkg/syncer/resources/ingress/uws.go
When using the ingress syncer and clusters with 1.20+ the ingress API has been moved to v1.20, this causes the syncer to fail. This updates the syncer to use the new API.
Fixes # <unfiled>
> 🌱 Update Ingress Syncer for v1.20 support

- virtualcluster/pkg/syncer/resources/crd/checker.go
- virtualcluster/pkg/syncer/resources/crd/uws.go
`c.MultiClusterController.GetCluster` method returns a pointer, but nil check was not done, so sometimes we could see the panic in logs, resulting syncer to be restarted or completely broken in that loop.
```
E0915 11:20:03.699391       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 6354 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1b6d040?, 0x30ce4b0})
/go/pkg/mod/k8s.io/apimachinery@v0.21.1/pkg/util/runtime/runtime.go:74 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc18faa20d0?})
/go/pkg/mod/k8s.io/apimachinery@v0.21.1/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1b6d040, 0x30ce4b0}) …
```
> 🐛 Handle GetCluster == nil in CRD uws

- virtualcluster/cmd/syncer/app/options/options.go
- virtualcluster/pkg/syncer/apis/config/types.go
- virtualcluster/pkg/syncer/resources/node/uws.go
- virtualcluster/pkg/syncer/vnode/native/provider.go
- virtualcluster/pkg/syncer/vnode/native/provider_test.go
- virtualcluster/pkg/syncer/vnode/pod/provider.go
- virtualcluster/pkg/syncer/vnode/provider/provider.go
- virtualcluster/pkg/syncer/vnode/service/provider.go
- virtualcluster/pkg/syncer/vnode/vnode.go
**What this PR does / why we need it**: 
***Context***:
The main reason for these changes is to allow VirtualCluster users to use pod.Spec.NodeSelector in their pods and choose nodes they want to be assigned. This would be extended after to auto-apply this nodeSelector for all pods in syncer if we want to have VirtualCluster fully isolated on the subset of nodes.
***Technical description***:
The PR adds sync of node Taints from super cluster to VirtualCluster to allow VirtualCluster pods to have tolerations.
The PR also extends the list of node labels to be synced to VirtualCluster, providing a new flag `--extra-node-labels=<stringslice>` to allow an operator to set the list of labels that need to be accessible by VirtualCluster users and used by them as node selectors.
***Tests***:
The …
> ✨ Sync node taints and labels

- virtualcluster/pkg/syncer/conversion/helper.go
- virtualcluster/pkg/syncer/resources/persistentvolume/uws_test.go
What type of PR is this?
/kind bug
What this PR does / why we need it:
Add Annotation UID of pPV to be synced to vPV, which is used to identify for consistency check.
Which issue(s) this PR fixes:
Fixes #
> 🐛 Add Annotation UID of pPV to be synced to vPV

- virtualcluster/pkg/syncer/resources/pod/checker.go
Because getting p/v objects in checker are not atomic operations. Here, we get the pList and vList cache in two steps with different time. As the number of clusters become more, there will be a greater difference. Some pPods will not be visible when Pods created during Checker run. This will trigger the pod force delete logic.
So, when finding that a vPod has been bound without pPod, we need double check whether the pPod exists before the pod force deletion.
**Which issue(s) this PR fixes** :
Fixes #308
> Fix Pod Checker occasionally deletes vPods unexpectedly

- virtualcluster/pkg/syncer/constants/constants.go
- virtualcluster/pkg/syncer/resources/pod/checker.go
- virtualcluster/pkg/syncer/resources/pod/dws.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
For certain tenants, they may be assigned with dedicated nodes and can schedule workload (pod) to these nodes with tenant scheduler. We would like to introduce a new label: "tenancy.x-k8s.io/tenant-scheduler" to let vc-syncer to be aware of the situation and skip the syncing.
Fixes # N/A
> ✨Bypass vc-syncing if tenant has own scheduler and dedicated node.

- virtualcluster/pkg/syncer/conversion/helper.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
In Kubernetes 1.20 the spec.preserveUnknownFields is not allowed to be set to true given Kubernetes has already deprecated this any cluster >=1.20 will not be able sync these resources, instead if a CRD has the field still set this disables that.
> 🐛 Handle deprecated preserveUnknownField in CRD spec

- virtualcluster/pkg/syncer/conversion/equality.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/uws.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/uws_test.go
Add PersistentVolumeClaim status upward sync. When we resize the storage of vPVC in VC, the CSI driver on the super cluster would update the pPVC.status.capacity after capacity expansion. Then we need to update vPVC status synchronously. 
This time, we only consider the capacity update, and other information (such as accessModes and phase) will not be synchronized.
**Which issue(s) this PR fixes**:
Relate: #322
/kind feature
> ✨ Add PersistentVolumeClaim status UWS

- virtualcluster/pkg/syncer/constants/constants.go
- virtualcluster/pkg/syncer/conversion/equality.go
- virtualcluster/pkg/syncer/conversion/helper.go
- virtualcluster/pkg/syncer/resources/configmap/checker.go
- virtualcluster/pkg/syncer/resources/configmap/checker_test.go
- virtualcluster/pkg/syncer/resources/configmap/dws.go
- virtualcluster/pkg/syncer/resources/configmap/dws_test.go
- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator.go
- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator_test.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
This PR adds feature gated support for VirtualCluster to work with any Kubernetes version +1.21 and when the `RootCACertConfigMap` feature is enabled in 1.20 clusters. To implement this rather than fighting the super cluster for the `kube-root-ca.crt` we will create a prefixed ConfigMap in each namespace `tenant-kube-root-ca.crt` and then when pods are synced we have an additional mutator that will rewrite the ConfigMap to the proper resource. This allows both super and tenant to work and requires no changes from a tenants workloads.
Fixes #293
> 🐛 v1.21 Support for RootCACertConfigMap feature

- virtualcluster/pkg/syncer/conversion/mutate.go
- virtualcluster/pkg/syncer/resources/service/dws_test.go
When DWS sync service creating, spec.clusterIPs should be empty, just like clusterIP.
**Which issue(s) this PR fixes** :
Fixes #325
>  🐛 Fix servcie mutator, reset pService ClusterIPs

- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator.go
- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator_test.go
After https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/326#discussion_r1017366793 was merged @wondywang noticed I missed InitContainers, this adds that capability as well.
Signed-off-by: Chris Hein <christopher_hein@apple.com>
> 🐛 InitContainer support for kube-root-ca.crt ConfigMaps

- virtualcluster/pkg/controller/controllers/provisioner/provisioner_native.go
This adds cluster labels to the tenant controlplane components to help with reporting all components/pods used for the cluster. We also use this to configure pod level networking so that Control Planes can have routable services from the APIServer. 
> 🌱 Adding Cluster Labels w/ Control Plane Components

- virtualcluster/pkg/syncer/conversion/equality.go
- virtualcluster/pkg/syncer/resources/configmap/checker.go
- virtualcluster/pkg/syncer/resources/configmap/checker_test.go
- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator.go
- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator_test.go
**What this PR does / why we need it** :
In this PR I would like to make volume.Projected support for kube-root-ca.crt ConfigMaps. And meanwhile renew the Checker to check  the TenantRootCACertConfigMapName in super.
**Which issue(s) this PR fixes** :
Fixes #
/kind feature
> 🌱 volume.Projected support for kube-root-ca.crt ConfigMaps

- virtualcluster/cmd/syncer/app/options/options.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
As a developer, when more and more feature gates are going to support, there will be some differences between different Syncer versions. In order to check the feature gate supported by a specific version, we hope to support `--help` to display all supported feature gates at current version.
it will output like this:
```bash
$./syncer --help
The resource syncer is a daemon that watches tenant clusters to
keep tenant requests are synchronized to super cluster by creating corresponding
custom resources on behalf of the tenant users in super cluster.
Usage:
syncer [flags]
Server flags:
--feature-gates mapStringBool
A set of key=value pairs that describe feature gates for various features.Options are:
ClusterVersionPartialUpgrade=true|false …
```
> 🌱 Update feature-gate util

- virtualcluster/pkg/syncer/conversion/helper.go
What type of PR is this?
/kind bug
What this PR does / why we need it:
As mentioned here, https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns, all namespace names must be valid RFC 1123 DNS labels.
> 🐛 namespace names should valid RFC 1123 DNS labels

- virtualcluster/cmd/manager/main.go
The PR adds a new flag `--leader-elect-resource-lock` to define the type of leader election resource lock (configmapleases, configmaps or leases). Current default behaviour of controller-runtime sets it to configmapleases, so the controller creates and updates two objects now - ConfigMap and Lease. Adding the flag would help operators to switch controller to use leases only to reduce load to the API and network.
The PR also deprecates the flag `--le-cm-name` because it was using `cm` in it, that could be confusing after the switch to leases; so it introduces the new flag `--leader-elect-resource-name` with the fallback to `--le-cm-name` if it is set explicitly.
> ✨  Add LeaderElectionResourceLock flag and generalize leaderElectionID flag name

- hack/ensure-kubectl.sh
/kind cleanup
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396
> 🌱 fix: use dl.k8s.io, not kubernetes-release bucket

- virtualcluster/pkg/syncer/conversion/equality.go
- virtualcluster/pkg/syncer/conversion/equality_test.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker_test.go
- virtualcluster/pkg/syncer/resources/persistentvolumeclaim/uws_test.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
The current syncer doesn't sync `PVC.Status.Phase` in a tenant cluster.  We have observed that a super cluster's PV and PVC are  not `Bound` while the the tenant cluster's PV and PVC are `Bound`, which might be caused by bug/race condition in the underlying controllers.  It should never happen. 
It can be reproduced by deleting a bound PVC in a tenant cluster, recreating the PVC and bound it again. The resulting PV and PVC in the tenant cluster will show `Bound` and the PV in the super cluster is `Released` and the PVC is `Pending`.
The PR updates a tenant cluster's PVC `Status.Phase` with the super cluster's `Status.Phase` if the tenant cluster PVC is `Bound` and the super cluster PVC is not `Bound`, e.g., `Pending`, `Lost`. The other conditions …
> Sync PVC's Status.Phase

- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podkubeapiaccessmutator.go
- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podkubeapiaccessmutator_test.go
- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podrootcacertmutator.go
- virtualcluster/pkg/syncer/util/featuregate/gate.go
This PR continue to improve the feature gated support for VirtualCluster to work with any Kubernetes version 1.21+ and when the RootCACertConfigMap feature is enabled in 1.20 clusters. To achieve this, before creating the pPod, the content in the kube-api-access volume is changed. Change it to directly mount the tenant cluster secret instead of applying the token of the super cluster.
Before:
```yaml
volumes:
- name: kube-api-access-sjz6l
projected:
defaultMode: 420
sources:
- serviceAccountToken:
expirationSeconds: 3607
path: token
- configMap:
items:
- key: ca.crt
path: ca.crt
name: kube-root-ca.crt
- downwardAPI:
items:
- fieldRef:
apiVersion: v1
fieldPath: metadata.namespace
path: namespace
```
After:
```yaml
volumes:
- name: …
```
> 🌱 Support for kube-api-access volume mount

- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podkubeapiaccessmutator.go
- virtualcluster/pkg/syncer/resources/pod/mutatorplugin/podkubeapiaccessmutator_test.go
Currently, #348 PodKubeAPIAccessMutatorPlugin not works and will get "error looking up serviceAccount ...." error, this PR will fix this issue 
Fixes #
> 🐛 fix pod kube-api-access sa not found

- virtualcluster/pkg/controller/util/net/util.go
The current implementation of kubectl-vc gets the first node in a cluster and stores its IP for the kubeconfig if the vc is set up with a nodeport service. This can cause issues if the chosen node's kubeproxy is down. Changing this to only select a ready node seems safer.
Before:
```
// GetNodeIP returns a node IP address
func GetNodeIP(cli client.Client) (string, error) {
nodeLst := &corev1.NodeList{}
if err := cli.List(context.TODO(), nodeLst); err != nil {
return "", err
}
if len(nodeLst.Items) == 0 {
return "", errors.New("there is no available nodes")
}
for _, addr := range nodeLst[0].Status.Addresses {
if addr.Type == corev1.NodeInternalIP {
return addr.Address, nil
}
}
return "", errors.New("there is no 'NodeInternalIP' type address")
}
``` …
> 🐛 GetNodeIP returns first ready node
