kubernetes-sigs/cluster-api-provider-nested

proposals/YYYYMMDD-template.md
This adds a proposals directory for as we put together the CAPN project allowing us to have clean plans for folks to work on.
=> Adds proposals directory and template so we document our designs

README.md
=> Adding Weekly call information

proposals/00_capn-glossary.md
=> Adding in-tree glossary for definitions

OWNERS_ALIASES
=> Add charleszheng44 to Approvers

.golangci.yml, Makefile, apis/controlplane/v1alpha4/nestedcontrolplane_types.go, certificate/helpers.go, certificate/keypairs.go, controllers/controlplane/controller_util.go, controllers/controlplane/nestedcontrolplane_controller.go, controllers/infrastructure/suite_test.go
This PR should be held open until after https://github.com/kubernetes/test-infra/pull/22090 is merged so we can test that the presubmit hooks is working.
closes #46 
=> 🌱 Reenabling more Lint tasks

virtualcluster/cmd/kubectl-vc/util.go
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
=> fix ineffectual assignment to err

docs/README.md
=> doc: add quick start guide for CAPN

docs/README.md
Fixed https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/74
=> updated how to connect to cluster

virtualcluster/pkg/syncer/conversion/equality.go
Signed-off-by: zhuangqh <zhuangqhc@gmail.com>
=> syncer: check meta equality for sa type token secret

Makefile
=> Updating staging and prod registries

Makefile
=> 🐛  target manifest pointed to wrong directory

Makefile
=> 🐛 control plane manifests weren't being pushed

cloudbuild.yaml
=> 🐛 removing docker/infra provider from cloudbuild

Makefile
=> 🍒  Cherrypick #106 🐛  Remove make release-binaries from make release

Makefile
=> 🐛 Remove make release-binaries from make release

Makefile
=> 🐛 remove docker release references

Makefile
=> 🐛 control plane manifests generated

Makefile
=> 🍒  Cherry Pick 🐛 control plane manifests generated

Makefile, config/manager/manager.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/kustomization.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, controlplane/nested/config/manager/manager.yaml, controlplane/nested/config/rbac/auth_proxy_role_binding.yaml, controlplane/nested/config/rbac/kustomization.yaml, controlplane/nested/config/rbac/leader_election_role_binding.yaml, controlplane/nested/config/rbac/role_binding.yaml, controlplane/nested/config/rbac/service_account.yaml
=> 🐛 Fix permission issues and wrong control plane image

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Add .github directory for cluster-api-provider-nested
Fixes #121
/cc @christopherhein @gyliu513
=> 🌱 Add .github directory from CAPI

docs/README.md
=> Update README to reflect latest code and way for init

virtualcluster/pkg/syncer/resources/endpoints/checker.go
Signed-off-by: zhuangqh <zhuangqhc@gmail.com>
syncer won't automatically remedy for custom endpoints(not generated from selector)
Fixes #
=> syncer: remedy for missmatched endpoints

virtualcluster/pkg/syncer/resources/namespace/checker.go
Signed-off-by: zhuangqh <zhuangqhc@gmail.com>
update namespace meta is a generic operation
Fixes #
=> syncer: remove feature guard when checking ns meta equality

virtualcluster/doc/demo.md, virtualcluster/experiment/doc/demo.md
=> Correct manifest path since the file name has been changed in previously ccommit

virtualcluster/config/setup/all_in_one.yaml, virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
Use a self-signed certificate for the virtual cluster webhook. See issue #125 for more details.
fixes #125
=> 🐛 use self-signed certificate for the virtualcluster webhook server

docs/README.md
with v0.4.0 cluster-api update, some steps are not needed anymore
Fixes #
=> update to reflect v0.4.0 cluster api

docs/README.md
=> Do not need to clone the repo before test

virtualcluster/pkg/util/mccontroller/mccontroller.go
The original implements can get the `Kind` when creating `MultiClusterController`, the `GroupVersionKind()` is empty.
=> Correct Kind setting for MultiClusterController

controlplane/nested/component-templates/nested-controllermanager/nested-controllermanager-statefulset-template.yaml, virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml, virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml, virtualcluster/pkg/controller/controllers/clusterversion_controller_test.go, virtualcluster/test/e2e/framework/clusterversion/create.go
=> Disable nodelifecycle controller to void NotReady status of virtual node

virtualcluster/pkg/syncer/conversion/equality.go
=> Avoid to diff ClusterIPs for SVC sync

virtualcluster/pkg/util/cluster/cluster.go
=> Terminal informer after tenant cluster removed

virtualcluster/doc/demo.md
=> update doc to make proxy step optional

virtualcluster/doc/demo.md
=> 📖Add info about usage of kubectl vc exec

controlplane/nested/controllers/nestedapiserver_controller.go
Fixes #
@christopherhein @Fei-Guo
=> Update variable name for fpcert

virtualcluster/pkg/syncer/conversion/equality.go
=> 🐛 add ipFamilies and ipFamilyPolicy into sync pre-set

controlplane/nested/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
Fixes #166 
This is a follow up for https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/166 to fix the issue in nested controller.
/cc @chrishenzie @Fei-Guo
=> Enabled aggregate API for nested controller

docs/dev-quickstart.md
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/181
This was blocked by https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/185 and @wangjsty is working on it.
/cc  @charleszheng44 @christopherhein
=> Added a dev quick start guide

controlplane/nested/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
Correct the value for requestheader-client-ca-file parameter
Fixes #185
=> Correct the value for requestheader-client-ca-file

docs/dev-quickstart.md
update doc to include minikube
Fixes #
=>  📖add minikube info into dev doc

controllers/nestedcluster_controller.go, main.go
=> ✨ Watch instead of loop check nested cluster

virtualcluster/pkg/controller/controllers/clusterversion_controller_test.go
=> 🌱 add test for "Enabled Aggregate API for Virtual Cluster"

virtualcluster/experiment/doc/demo.md
The `CRD` path is not correct.
Fixes #
=> Correct crd link for experiment

virtualcluster/cmd/syncer/app/options/options.go
Follow up from - https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/256#discussion_r823165992
=> 🌱 Adding Timeout duration units

.github/workflows/golangci-lint.yml, controlplane/nested/controllers/controller_util.go, controlplane/nested/main.go, main.go
Since #267 was merged we hadn't tested golangci-lint w/ GitHub actions, this is attempting to fix the issues with the setup.
=> 🐛 Github Actions goreleaser fixes

virtualcluster/cmd/manager/main.go, virtualcluster/pkg/controller/util/kube/util.go
This PR adds feature gate support to virtualcluster manager and uses SuperClusterLabelling feature to label virtualcluster root namespaces too.
Fixes #275
=> ✨ Add SuperClusterLabelling experimental feature gate to manager

virtualcluster/pkg/syncer/syncer.go
https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/287 accidentally removed important piece of code. 
The PR returns this code back
=> 🐛 Return syncer start workers

virtualcluster/pkg/syncer/conversion/mutate.go, virtualcluster/pkg/syncer/conversion/mutate_test.go
**What type of PR is this?**
/kind feature
This PR support exposing single annotations/labels via env downward API.
**Which issue(s) this PR fixes**:
Fixes #297
=> ✨Support exposing single annotations/labels via env downward API

virtualcluster/config/sampleswithspec/coredns_external.yaml, virtualcluster/pkg/controller/controllers/virtualcluster_controller_test.go, virtualcluster/pkg/syncer/conversion/equality.go, virtualcluster/pkg/syncer/resources/service/uws.go, virtualcluster/pkg/syncer/util/featuregate/gate.go
Enhancement for virtual cluster DNS: https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/329
Fixes #329
=> ✨ Enhancement for virtual cluster DNS
